# Generated by Django 4.2.4 on 2023-09-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('product_label', models.IntegerField(choices=[(1, '아이스크림'), (2, '스낵'), (3, '음료'), (4, '라면')])),
                ('objectcount', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kiosk',
                'db_table': 'Kiosk',
            },
        ),
    ]
