# Generated by Django 4.2.4 on 2023-08-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('objectcount', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Kiosk',
            },
        ),
    ]
